### ISSUE TITLE
Fetus is somehow added to creature list which causes NPE

### ISSUE THREAD

**Issue by mibac138** [mibac138/Dot-life-simulator#1]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at java.awt.geom.Point2D.distance(Unknown Source)
    at com.mibac.dots.wen.ai.EntityAI.lambda$0(EntityAI.java:48)
    at com.mibac.dots.wen.ai.EntityAI$$Lambda$15/687794088.compare(Unknown Source)
    at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
    at java.util.TimSort.sort(Unknown Source)
    at java.util.Arrays.sort(Unknown Source)
    at java.util.Vector.sort(Unknown Source)
    at java.util.Collections.sort(Unknown Source)
    at com.mibac.dots.wen.ai.EntityAI.getCreaturesInRange(EntityAI.java:46)
    at com.mibac.dots.wen.ai.EntityAI.update(EntityAI.java:23)
    at com.mibac.dots.wen.creatures.Creature.update(Creature.java:72)
    at com.mibac.dots.wen.Creatures.actionPerformed(Creatures.java:84)
    at javax.swing.Timer.fireActionPerformed(Unknown Source)
    at javax.swing.Timer$DoPostEvent.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Edit** I **do** know how to mute it but muting it doesn't solve the actual problem which can cause AIs to go to fetuses.

**Comment by mibac138** [comment]
Fixing in progress. 

**Edit**
After a lot of headache fixed it.

**Edit 2**
Pushed commit with fix https://github.com/mibac138/Dot-life-simulator/commit/abdeab52f72e566c53dea50cdc893c8f44304edd
